version: '3.8'

services:
  backend:
    image: backend-app
    build:
      context: ./star_wars_card_collector
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    image: frontend-app
    build:
      context: ./star_wars_card_collector_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
    driver: local
